# Generated by Django 4.2.4 on 2024-03-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
