# Generated by Django 4.2.4 on 2024-03-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_quote_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmark',
            field=models.ManyToManyField(blank=True, to='words.quote'),
        ),
    ]
