# Generated by Django 4.2.4 on 2024-03-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_user_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmark',
            field=models.ManyToManyField(blank=True, db_index=True, to='words.quote'),
        ),
    ]
