# Generated by Django 4.2.4 on 2024-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_user_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookmark',
            field=models.ManyToManyField(blank=True, to='words.quote'),
        ),
    ]
