# Generated by Django 4.2.4 on 2024-04-02 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_alter_user_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
