# Generated by Django 4.2.4 on 2024-04-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_user_bookmarked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmarked_at',
        ),
    ]
